kind: pipeline
type: docker
name: photolum

steps:
- name: build
  image: golang:1.15-buster
  commands:
  - export GO111MODULE=on &&
    export GOOS=linux &&
    export GOARCH=amd64 &&
    export CGO_ENABLED=1 &&
    go build -o photolum cmd/main.go
  when:
    branch:
    - master
    event:
    - push
- name: publish
  image: plugins/docker
  settings:
    username:
      from_secret: docker_username
    password: 
      from_secret: docker_password
    repo: paulwrubel/photolum
    tags:
    - latest
