kind: pipeline
type: docker
name: photolum

clone:
  disable: true

steps:
- name: clone
  image: alpine/git
  commands:
  - git init .
  - git add remote origin https://github.com/paulwrubel/photolum.git
  - du -sh .
  - git config core.sparseCheckout true
  - echo -e "/*\n!sample-output/\n!resources/" >> .git/info/sparse-checkout
  - cat .git/info/sparse-checkout
  - git pull
  - du -sh .
  - git checkout $DRONE_COMMIT

- name: build
  image: golang:1.15-buster
  commands:
  - export GO111MODULE=on &&
    export GOOS=linux &&
    export GOARCH=amd64 &&
    export CGO_ENABLED=0 &&
    go build -o photolum cmd/main.go
  when:
    branch:
    - master
    event:
    - push
    - pull_request

- name: publish
  image: plugins/docker
  settings:
    username:
      from_secret: docker_username
    password: 
      from_secret: docker_password
    repo: paulwrubel/photolum
    tags:
    - latest
  when:
    branch:
    - master
    event:
    - push
